# Generated by Django 5.2 on 2025-07-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_remove_joblisting_description_joblisting_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
